# The format which the backup file names follow.
# You can use %%date%% here to insert the date. The format of the date can be
# changed below.
file-name: 'backup-%%date%%.zip'

# The format which dates in the backup file names follow.
# See https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html for more info.
date-format: 'dd-MM-yyyy-HHmm'

# The higher this number is, the more the zip file will be compressed.
# A higher compression level means the zip file will be smaller, but it
# will also take longer to generate.
# The maximum compression level is 9.
compression-level: 9

# The maximum size of the backup folder. If the backup folder exceeds this size,
# the oldest backup is deleted. This amount is in GB.
# You can also set this to -1 to disable automatic deletion of old backups.
max-backup-folder-size: 10

# The files and folders specified here will not be included in a backup.
# You can add more entries, but removing the ones included by default is
# not recommended.
exempt:
  - 'backups'
  - 'logs'
  - 'cache'
  - 'server.jar'