name: EasierBackup
version: ${project.version}
author: MisterMel
main: tech.mistermel.easierbackup.EasierBackup
commands:
  easierbackup:
    description: Main command
    aliases: ['backup']
    permission: 'easierbackup.admin'
